### ISSUE TITLE
Support other docstring types

### ISSUE THREAD

**Issue by notmatthancock** [jdidion/autoclick#16]
Only Google style docstrings are currently supported:
https://github.com/jdidion/autoclick/blob/05dd571e212672d6d793b2b74428cf40b505c494/autoclick/core.py#L245-L246

**Comment by notmatthancock** [comment]
If https://github.com/rr-/docstring_parser were to be used instead of the current parsing library, then google, numpy, and rest styles would be supported with minimal changes to the existing code. I'd be glad to make a PR with this change if desired.

**Comment by jdidion** [comment]
That would be much appreciated, thanks!
